In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier, export_graphviz

In [24]:
cd Desktop

[WinError 2] The system cannot find the file specified: 'Desktop'
C:\Users\admin\Desktop


In [25]:
df = pd.read_excel("bloodDonation.xlsx",names = ['Recency','Frequency','Monetary','Time','Blood Donated'])
df.head()

Recency  Frequency  Monetary  Time  Blood Donated
0        0         13      3250    28              1
1        1         16      4000    35              1
2        2         20      5000    45              1
3        1         24      6000    77              0
4        4          4      1000     4              0

In [26]:
X=df.iloc[:,0:4]
X.head()

Recency  Frequency  Monetary  Time
0        0         13      3250    28
1        1         16      4000    35
2        2         20      5000    45
3        1         24      6000    77
4        4          4      1000     4

In [27]:
Y=df.iloc[:,4]
Y.head()

0    1
1    1
2    1
3    0
4    0
Name: Blood Donated, dtype: int64

In [28]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [29]:
 #install pydotplus using command : pip install pydotplus
import pydotplus
import io

In [30]:
from IPython.display import Image

In [38]:
def visualize_tree(tree, feature_names):
    """Create tree png using graphviz.

    Args
    ----
    tree -- scikit-learn DecsisionTree.
    feature_names -- list of feature names.
    """
    with open("bloodDonatedCopy.dot", 'w') as f:
        export_graphviz(tree, out_file=f,
                        feature_names=feature_names)

    command = ['dot', 'Tpng', 'bloodDonatedCopy.dot', '-o', 'bloodDonatedCopy.png']
    try:
        subprocess.check_call(command)
    except:
        exit("Could not run dot, ie graphviz, to "
             "produce visualization")

In [39]:
visualize_tree(clf, features)

In [35]:
#download graphviz for python --- graphviz 2.38 zip file.
# Extract and put folder in C:\Program Files X86.
# Note: No need to run any exe.
#set environment variable in Control Panel - System - path => C:\Program Files (x86)\graphviz-2.38\release\bin
graph = pydotplus.graph_from_dot_file('bloodDonatedCopy.dot')

In [36]:
graph.write_pdf("bloodDonatedCopy.pdf")

True

In [44]:
ndTest=np.matrix([[2,6,1500,15],[4,11,2750,28]])

In [45]:
clf.predict(ndTest)

array([1, 0], dtype=int64)

In [50]:
ndTest=np.matrix([[2,6,1500,15],[0,13,3250,28]])

In [51]:
clf.predict(ndTest)

array([1, 1], dtype=int64)

In [52]:
ndTest=np.matrix([[16,1,250,16]])

In [53]:
clf.predict(ndTest)

array([0], dtype=int64)